ALTER TABLE "Session"
ADD COLUMN "isArchived" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "archivedAt" TIMESTAMP(3),
ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Device" ALTER COLUMN "updatedAt" DROP DEFAULT;
ALTER TABLE "Session" ALTER COLUMN "updatedAt" DROP DEFAULT;
